'use client';
import {useEffect,useState} from 'react';
import {OceanData} from '@/lib/types';
type Row={depth:number;observed_depth:number;observed:number;baseline:number;departure:number;statistical_count:number|null;statistical_std:number|null};
type Result={status:string;message?:string;method?:string;observed_at?:string;last_successful_sync?:string;data_mode?:string;source?:string;variables?:Record<string,{rows:Row[];source:string;title:string;units:string;grid_latitude:number;grid_longitude:number}>};
export function AnomalyOverlay({data}:{data:OceanData}){
 const [id,setId]=useState('');const [result,setResult]=useState<Result>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [version,setVersion]=useState(0);
 const selected=data.profiles.find(p=>p.profile_id===id)??data.profiles.at(-1);
 useEffect(()=>{if(!selected)return;let alive=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
 async function read(){try{const r=await fetch('/api/baseline?profile_id='+encodeURIComponent(selected!.profile_id),{signal:controller.signal});const value=await r.json();if(!r.ok)throw Error(value.error||value.detail||'Baseline service unavailable');if(alive){setResult(value);setError('');if(value.status==='syncing')timer=setTimeout(read,2000)}}catch(e){if(alive)setError(String(e))}}
 setResult(undefined);void read();return()=>{alive=false;controller.abort();clearTimeout(timer)}},[selected?.profile_id,version]);
 async function sync(){if(!selected)return;setBusy(true);setError('');try{const r=await fetch('/api/baseline?profile_id='+encodeURIComponent(selected.profile_id),{method:'POST'});const value=await r.json();if(!r.ok)throw Error(value.error||value.detail||'Sync unavailable');setVersion(v=>v+1)}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <div className="panel" style={{padding:24}}><span className="pill">NOAA WOA23 · 1991–2020</span><h3>Observed departures from seasonal climatology</h3><p>Compare a real profile with its calendar-month baseline. Positive values are warmer or saltier than climatology.</p>
 <label>ARGO profile <select aria-label="Climatology profile" value={selected?.profile_id||''} onChange={e=>setId(e.target.value)} style={{maxWidth:'100%',background:'#102a34',color:'#deeff0',padding:10}}>{data.profiles.map(p=><option key={p.profile_id} value={p.profile_id}>{p.float_id} / {p.cycle} · {p.timestamp.slice(0,10)}</option>)}</select></label>{' '}
 <button className="btn" onClick={sync} disabled={!selected||busy||result?.status==='syncing'}>{busy||result?.status==='syncing'?'Syncing NOAA…':result?.status==='error'?'Retry NOAA sync':'Sync official NOAA baseline'}</button>
 <p role="status" aria-live="polite">{error||result?.message||(result?.status==='ready'?'Official climatology cached and available.':selected?'No validated baseline for this observation month. Sync to download it.':'Load ARGO observations first.')}</p>
 {result?.last_successful_sync&&<p>Last successful sync: {result.last_successful_sync} · Observation: {result.observed_at} · Data mode: {result.data_mode}</p>}
 {Object.entries(result?.variables||{}).map(([name,v])=><article key={name}><h4>{name==='temperature'?'Temperature':'Salinity'} · {v.units}</h4><p>{v.title} · Grid cell {v.grid_latitude}°, {v.grid_longitude}° · {v.rows.length} matched standard levels</p>{v.rows.length?<div style={{overflow:'auto',maxHeight:300}}><table style={{width:'100%',textAlign:'left'}}><thead><tr>{['WOA depth m','Observed depth m','Observed','Climatology','Departure','Cell count','Cell SD'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{v.rows.map(r=><tr key={r.depth}><td>{r.depth}</td><td>{r.observed_depth.toFixed(1)}</td><td>{r.observed.toFixed(3)}</td><td>{r.baseline.toFixed(3)}</td><td style={{color:r.departure>=0?'#ffd091':'#79e8d4'}}>{r.departure>0?'+':''}{r.departure.toFixed(3)}</td><td>{r.statistical_count??'Unavailable'}</td><td>{r.statistical_std?.toFixed(3)??'Unavailable'}</td></tr>)}</tbody></table></div>:<p>No QC-accepted observations within 5 m of a valid climatology level.</p>}<p><a href={v.source} target="_blank" rel="noreferrer">Official NOAA NetCDF ↗</a></p></article>)}
 {result?.source&&<p><a href={result.source} target="_blank" rel="noreferrer">ARGO observation file ↗</a></p>}<p className="muted">{result?.method||'Seasonal departures require a validated NOAA cache. No marine heatwave classification is performed.'}</p></div>
}
