'use client';
import type {Gradient} from './DepthAnalysis';
import { Profile, WAITING } from '@/lib/types';
import { ProvenanceInfo } from './DataProvenance';
export function ProfileChart({profile,variable,onDepth,depth,analysis}:{profile?:Profile;variable:'temperature'|'salinity';onDepth:(v:number)=>void;depth:number;analysis?:Gradient}){
 const points=profile?.samples.filter(s=>s[variable]!==null)??[];
 const values=points.map(s=>s[variable] as number);const min=Math.min(...values),max=Math.max(...values);const bottom=Math.max(1,...points.map(s=>s.depth));
 const x=(v:number)=>55+(v-min)/Math.max(.01,max-min)*310;const y=(d:number)=>28+d/bottom*205;
 const strongest=analysis?.candidate;
 return <div className="chart"><div className="chart-title"><h3>{variable==='temperature'?'Temperature':'Salinity'} <span>{variable==='temperature'?'°C':'PSU'}</span></h3><ProvenanceInfo profile={profile}/></div>{points.length>1?<><svg viewBox="0 0 400 270" role="img" aria-label={`${variable} versus depth`} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();onDepth(Math.max(0,Math.min(bottom,((e.clientY-r.top)/r.height*270-28)/205*bottom)))}}>{[0,.25,.5,.75,1].map(v=><g key={v}><line x1="55" x2="365" y1={y(v*bottom)} y2={y(v*bottom)} stroke="#173443"/><text x="44" y={y(v*bottom)+4} textAnchor="end" fill="#899fa9" fontSize="11">{Math.round(v*bottom)}</text></g>)}<path d={points.map((p,i)=>`${i&&p.depth-points[i-1].depth<=150?'L':'M'}${x(p[variable] as number)},${y(p.depth)}`).join(' ')} fill="none" stroke={variable==='temperature'?'#66e7ce':'#7caeff'} strokeWidth="2"/>{strongest&&<line x1="55" x2="365" y1={y(strongest.depth)} y2={y(strongest.depth)} stroke="#f3c587" strokeDasharray="4 5"/>}{depth<=bottom&&<line x1="55" x2="365" y1={y(depth)} y2={y(depth)} stroke="white" opacity=".5"/>}<text x="55" y="259" fill="#899fa9" fontSize="12">{min.toFixed(2)}</text><text x="335" y="259" fill="#899fa9" fontSize="12">{max.toFixed(2)}</text></svg><p className="chart-foot">{variable==='temperature'?'Thermocline candidate':'Strongest salinity gradient'}: {strongest?.depth.toFixed(0)??'—'} m{strongest&&<> · {strongest.slope.toFixed(4)} {variable==="temperature"?"°C/m":"PSU/m"} <button onClick={()=>onDepth(strongest.depth)}>Inspect layer</button></>} · hover to link depth</p><p className="chart-foot">{analysis?.message??"Depth analysis pending"} · {analysis?.coverage??"Coverage not assessed"}. QC 1 local regression; see calculation method below.</p></>:<div className="chart-empty"><div className="empty-axis"><span>DEPTH / m</span></div><span>{WAITING}</span><small>{variable==='temperature'?'Thermocline analysis':'Salinity gradient analysis'} pending quality-controlled profiles</small></div>}</div>
}
