'use client';
import {useEffect,useState} from 'react';
type SyncState={status:string;message:string;last_attempt?:string;result?:{regions:{region:string;float_id:string;profiles:number;newest_observation:string}[];warnings:string[]}};
export function SyncLatest({onComplete}:{onComplete:()=>void}){
 const [state,setState]=useState<SyncState>({status:'idle',message:'Discover the newest QC-approved profiles in both regions (120-day search window).'});
 useEffect(()=>{if(state.status!=='running')return;let busy=false;const id=setInterval(async()=>{if(busy)return;busy=true;try{const r=await fetch('/api/sync',{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Sync status unavailable');const value=await r.json();setState(value);if(value.status==='complete')onComplete()}catch{setState({status:'error',message:'Cannot reach data service. Existing cached observations remain available.'})}finally{busy=false}},3000);return()=>clearInterval(id)},[state.status,onComplete]);
 async function start(){setState({status:'running',message:'Connecting to official GDAC…'});try{const r=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error();setState(await r.json())}catch{setState({status:'error',message:'Could not start sync. Check the Python data service and retry; cached data is unchanged.'})}}
 return <div className="connection-banner"><button className="sync-button" disabled={state.status==='running'} onClick={start}>{state.status==='running'?'Syncing ARGO…':'Sync latest ARGO'}</button><p role="status">{state.message}</p>{state.last_attempt&&<small>Last attempt: {state.last_attempt}</small>}{state.result&&<div>{state.result.regions.map(r=><p key={r.region}>{r.region}: {r.float_id} · {r.profiles} profiles · newest observation {r.newest_observation}</p>)}{state.result.warnings.length>0&&<details><summary>{state.result.warnings.length} source warnings</summary>{state.result.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}</div>}<small>Downloads a bounded recent subset. Historical observations are preserved. Sync time is not observation time.</small></div>
}
